/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp3ejer2;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author camila biarnes
 */
public class frmConversor extends javax.swing.JFrame {

    /**
     * Creates new form frmConversor
     */
    ButtonGroup grupoBotones;
    
   public frmConversor() {
        initComponents();
        // Agrupamos los radio buttons
        grupoBotones = new ButtonGroup();
        grupoBotones.add(btnFah);
        grupoBotones.add(btnKel);
        grupoBotones.add(btnCel);
        grupoBotones.add(btnRaf);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrMedida = new javax.swing.ButtonGroup();
        btnFah = new javax.swing.JRadioButton();
        btnKel = new javax.swing.JRadioButton();
        btnCel = new javax.swing.JRadioButton();
        btnRaf = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtBox = new javax.swing.JTextField();
        btnConvert = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgrMedida.add(btnFah);
        btnFah.setText("a Fahrenheit");
        btnFah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFahActionPerformed(evt);
            }
        });

        bgrMedida.add(btnKel);
        btnKel.setText("a Kelvin");
        btnKel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelActionPerformed(evt);
            }
        });

        bgrMedida.add(btnCel);
        btnCel.setText("a  Celsius");
        btnCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCelActionPerformed(evt);
            }
        });

        bgrMedida.add(btnRaf);
        btnRaf.setText("a Radianes");
        btnRaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRafActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("INGRESE TEMPERATURA EN GRADOS");

        txtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBoxActionPerformed(evt);
            }
        });

        btnConvert.setText("CONVERTIR");
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CONVERSOR DE TEMPERATURA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFah)
                            .addComponent(btnKel))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCel)
                            .addComponent(btnRaf)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(txtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(btnConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel2)
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(txtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFah)
                    .addComponent(btnCel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRaf)
                    .addComponent(btnKel))
                .addGap(34, 34, 34)
                .addComponent(btnConvert)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFahActionPerformed

    private void txtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoxActionPerformed

    private void btnKelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKelActionPerformed

    private void btnCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCelActionPerformed

    private void btnRafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRafActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRafActionPerformed

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed
        // TODO add your handling code here:
         try {
        double valor = Double.parseDouble(txtBox.getText());
        double resultado = 0.0;
        String mensaje = "";

        
        if (btnFah.isSelected()) {
            resultado = valor * 9/5 + 32; // Celsius a Fahrenheit
            mensaje = valor + " °C son " + resultado + " °F";
        } else if (btnKel.isSelected()) {
            resultado = valor + 273.15; // Celsius a Kelvin
            mensaje = valor + " °C son " + resultado + " K";
        } else if (btnCel.isSelected()) {
            mensaje = "Ya estás en Celsius: " + valor + " °C";
        } else if (btnRaf.isSelected()) {
            mensaje = "Conversión no válida (Radianes no aplica a temperatura)";
        } else {
            mensaje = "Selecciona una opción de conversión.";
        }

        // Mostrar el resultad
        JOptionPane.showMessageDialog(this, mensaje);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido.");
    }
    }//GEN-LAST:event_btnConvertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmConversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrMedida;
    private javax.swing.JRadioButton btnCel;
    private javax.swing.JButton btnConvert;
    private javax.swing.JRadioButton btnFah;
    private javax.swing.JRadioButton btnKel;
    private javax.swing.JRadioButton btnRaf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtBox;
    // End of variables declaration//GEN-END:variables
}
